before_install:
    - docker build -t listx/texlive:2016 github.com/aldoridhoni/texlive-docker.git#master:texlive
    - docker build -t aldoridhoni/texlive:2016-fonts github.com/aldoridhoni/texlive-docker.git#master:texlive-with-fonts
    - docker run --detach --volume `pwd`:/home/repo --name texlive2016 aldoridhoni/texlive:2016-fonts
    - docker ps -a
services:
    - docker
script:
    - docker exec texlive2016 sh -c "sh /etc/profile.d/perlbin.sh && cd /home/repo && make pdf"
language: latex
