before_install:
    - docker pull listx/texlive:2016-fonts
    - docker run --detach --volume `pwd`:/home/repo --name texlive2016 listx/texlive:2016-fonts
    - docker ps -a
services:
    - docker
script:
    - docker exec texlive2016 sh -c "cd /home/repo && make pdf"
language: latex
