before_install:
    - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng python-pygments"
    - tlmgr install logreq
script:
    make pdf
os: linux
dist: trusty
